/InterfaceExample/geometry/SetGasPressure 0.6 bar
/InterfaceExample/geometry/setup TPC

/gasModelParameters/heed/heedinterface/addparticle e- 0. 0.001
/gasModelParameters/heed/heedinterface/addparticle gamma 0. 10000000
/gasModelParameters/heed/heedonly/addparticle e- 1000. 100000.
/gasModelParameters/heed/heedonly/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heedonly/addparticle p 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle pi 1000. 1000000.

/gasModelParameters/heed/gasfile /mnt/ksf9/H2/user/u0111340/linux/AliceTPC/AliceTPC/Ne_90_CO2_10_N2_5_with_mg.gas
/gasModelParameters/heed/ionmobilityfile IonMobility_Ne+_Ne.txt
/gasModelParameters/heed/drift 1
/gasModelParameters/heed/driftRKF 1
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 0
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 0
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100000
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 1460.
/gasModelParameters/heed/voltagecathodewire 0.
/gasModelParameters/heed/voltagegate -70.
/gasModelParameters/heed/voltagedeltagate 90.
/gasModelParameters/degrad/thermalenergy 10. eV

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp
/InterfaceExample/phys/InitializePhysics emlivermore
/InterfaceExample/phys/AddParametrisation
/process/em/AddPAIRegion all RegionGasBox PAIPhoton

/InterfaceExample/phys/setLowLimitE 20. eV
#/random/setSeeds 0 0
/run/initialize

/param/InActivateModel DegradModel
/param/InActivateModel GarfieldVUVPhotonModel

/analysis/setFileName test

####################################
############ Verbosities ###########
####################################
/tracking/verbose 0
/run/verbose 1
/event/verbose 0

####################################
########### Visualization ##########
####################################

/vis/open VRML2FILE
#/vis/open OGL 600x600-0+0

/run/verbose 2
/event/verbose 0
/tracking/verbose 0

# Draw geometry:
/vis/drawVolume

# Draw smooth trajectories at end of event.
# Gamma-rays represented in red.
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma red
/vis/modeling/trajectories/drawByParticleID-0/set e- green
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton blue
#Set Visualization properties
/vis/scene/add/axes

/vis/scene/endOfEventAction accumulate 10
/vis/scene/endOfRunAction accumulate
/vis/geometry/set/forceSolid GasBox -1 1
/vis/geometry/set/forceSolid FieldWire -1 1
/vis/geometry/set/forceSolid SignalWire -1 1
/vis/geometry/set/forceSolid cell_logical -1 1
/tracking/storeTrajectory 0 
/vis/scene/add/trajectories

/gps/particle pi+
/gps/ene/type Mono
/gps/ene/mono 1 GeV
# Positioning and Angles
#/gps/source/intensity 49000
/gps/pos/confine Carrier
/gps/ang/type iso
#/gps/ang/minphi 240 deg
#/gps/ang/maxphi 300 deg
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 1 mm
/gps/pos/halfz 30 nm
/gps/pos/rot2 0 0 1


/run/beamOn 1
