/ALICE/geometry/SetGasPressure 0.6 bar

/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0. 0.001
/gasModelParameters/heed/heeddeltaelectron/addparticle gamma 0. 10000000
/gasModelParameters/heed/heednewtrack/addparticle e- 0.1 100000.
/gasModelParameters/heed/heednewtrack/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heednewtrack/addparticle proton 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heednewtrack/addparticle mu 1000. 1000000.
#/gasModelParameters/heed/heednewtrack/addparticle pi+ 100. 1000000.

/gasModelParameters/heed/gasfile /mnt/ksf9/H2/user/u0111340/linux/AliceTPC/AliceTPC/Ne_90_CO2_10_N2_5_with_mg.gas
/gasModelParameters/heed/ionmobilityfile IonMobility_Ne+_Ne.txt
/gasModelParameters/heed/drift 0
/gasModelParameters/heed/driftRKF 1
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 0
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 0
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100000
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 1460.
/gasModelParameters/heed/voltagecathodewire 0.
/gasModelParameters/heed/voltagegate -70.
/gasModelParameters/heed/voltagedeltagate 90.

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp
/ALICE/phys/setLowLimitE 20. eV
/ALICE/phys/InitializePhysics emlivermore
/ALICE/phys/AddParametrisation
/process/em/AddPAIRegion all RegionGasBox PAIPhoton

#/random/setSeeds 0 0
/run/initialize

#/param/InActivateModel HeedNewTrackModel
#/param/InActivateModel HeedDeltaElectronModel

/analysis/setFileName test

####################################
############ Verbosities ###########
####################################
/tracking/verbose 0
/run/verbose 1
/event/verbose 0

####################################
########### Visualization ##########
####################################
/gps/particle proton
/gps/position 0. 0. 0. cm
/gps/direction 1. 0. 0.
/gps/ene/type Mono
/gps/ene/mono 2000 MeV

/run/beamOn 1
