/InterfaceExample/geometry/SetGasPressure 0.6 bar
/InterfaceExample/geometry/setup TPC

#/gasModelParameters/heed/heedinterface/addparticle e- 0. 0.001
#/gasModelParameters/heed/heedinterface/addparticle gamma 0. 10000000
/gasModelParameters/heed/heedonly/addparticle e- 0.1 100000.
/gasModelParameters/heed/heedonly/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heedonly/addparticle proton 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu 1000. 1000000.
#/gasModelParameters/heed/heedonly/addparticle pi+ 100. 1000000.

/gasModelParameters/heed/gasfile /mnt/ksf9/H2/user/u0111340/linux/AliceTPC/AliceTPC/Ne_90_CO2_10_N2_5_with_mg.gas
/gasModelParameters/heed/ionmobilityfile IonMobility_Ne+_Ne.txt
/gasModelParameters/heed/drift 0
/gasModelParameters/heed/driftRKF 1
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 0
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 0
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100000
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 1460.
/gasModelParameters/heed/voltagecathodewire 0.
/gasModelParameters/heed/voltagegate -70.
/gasModelParameters/heed/voltagedeltagate 90.
/gasModelParameters/degrad/thermalenergy 10. eV

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp
/InterfaceExample/phys/setLowLimitE 20. eV
/InterfaceExample/phys/InitializePhysics emlivermore
/InterfaceExample/phys/AddParametrisation
/process/em/AddPAIRegion all RegionGasBox PAIPhoton

#/random/setSeeds 0 0
/run/initialize

/param/InActivateModel DegradModel
/param/InActivateModel GarfieldVUVPhotonModel

/analysis/setFileName test

####################################
############ Verbosities ###########
####################################
/tracking/verbose 0
/run/verbose 1
/event/verbose 0

####################################
########### Visualization ##########
####################################
/gps/particle proton
/gps/position 0. 0. 0. cm
/gps/direction 1. 0. 0.
/gps/ene/type Mono
/gps/ene/mono 2000 MeV
# Positioning and Angles
#/gps/source/intensity 49000
#/gps/ang/type iso
#/gps/ang/minphi 240 deg
#/gps/ang/maxphi 300 deg
#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/radius 1 mm
#/gps/pos/halfz 30 nm
#/gps/pos/rot2 0 0 1

/run/beamOn 1
